---
title: "Iowa Productivity Index Comparison"
author: "J. Stephenson"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE, 
                      message = FALSE)#,
                      #fig.width = 12,
                      #fig.height = 12)

library("tidyverse"); theme_set(theme_bw())
library("lme4")
library("lmerTest")
library("emmeans")
library("ggResidpanel")

options(width = 200)

dir.create("fig", showWarnings = FALSE)
```

```{r create_cpi, cache.extra=tools::md5sum("../data/raw/ia_cpi.csv")}
## Generate dataframe
ia_CPI <- read_csv("../data/raw/ia_cpi.csv") %>%
  mutate(NCCPIx100 = NCCPIall * 100,
         cpi_diff = abs(OCProdIdx - NCCPIx100),
         state = "IA")

il_CPI <- read_csv("../data/raw/il_cpi.csv") %>%
  mutate(NCCPIx100 = NCCPIall * 100,
         cpi_diff = abs(OCProdIdx - NCCPIx100),
         state = "IL")

in_CPI <- read_csv("../data/raw/in_cpi.csv") %>%
  mutate(NCCPIx100 = NCCPIall * 100,
         cpi_diff = abs(OCProdIdx - NCCPIx100),
         state = "IN")

mn_CPI <- read_csv("../data/raw/mn_cpi.csv") %>%
  mutate(NCCPIx100 = NCCPIall * 100,
         cpi_diff = abs(OCProdIdx - NCCPIx100),
         state = "MN")

oh_CPI <- read_csv("../data/raw/oh_cpi.csv") %>%
  mutate(NCCPIx100 = NCCPIall * 100,
         cpi_diff = abs(OCProdIdx - NCCPIx100),
         state = "OH")

wi_CPI <- read_csv("../data/raw/wi_cpi.csv") %>%
  mutate(NCCPIx100 = NCCPIall * 100,
         cpi_diff = abs(OCProdIdx - NCCPIx100),
         state = "WI")

CPI_df <- rbind(ia_CPI, il_CPI, in_CPI, mn_CPI, oh_CPI, wi_CPI)

CPI_df50 <- filter(CPI_df, NCCPIx100 < 50)

```

```{r explore_cpi 2, dependson="create_cpi"}

## explore summary statistics of dataset
str(CPI_df50)
summary(CPI_df50)

```


```{r explore_cpi, dependson="create_cpi"}
#ggplot(CPI_df50, aes(x = OCProdIdx, y = NCCPIx100, color = state)) +
ggplot(ia_CPI, aes(x = OCProdIdx, y = NCCPIx100)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", color = "blue") +
  labs(title = "CSR2 vs State-level Index", x = "State-level Index", y = "NCCPI")

```


```{r cpi_cor, dependson = "create_cpi", eval = FALSE, echo = FALSE}
cor.test(ia_CPI$OCProdIdx, ia_CPI$NCCPIx100, method = "pearson")  # linear correlation
cor.test(ia_CPI$OCProdIdx, ia_CPI$NCCPIx100, method = "spearman") # rank-based (non-parametric)

cor.test(il_CPI$OCProdIdx, il_CPI$NCCPIx100, method = "pearson")  # linear correlation
cor.test(il_CPI$OCProdIdx, il_CPI$NCCPIx100, method = "spearman") # rank-based (non-parametric)

cor.test(in_CPI$OCProdIdx, in_CPI$NCCPIx100, method = "pearson")  # linear correlation
cor.test(in_CPI$OCProdIdx, in_CPI$NCCPIx100, method = "spearman") # rank-based (non-parametric)

cor.test(mn_CPI$OCProdIdx, mn_CPI$NCCPIx100, method = "pearson")  # linear correlation
cor.test(mn_CPI$OCProdIdx, mn_CPI$NCCPIx100, method = "spearman") # rank-based (non-parametric)

cor.test(oh_CPI$OCProdIdx, oh_CPI$NCCPIx100, method = "pearson")  # linear correlation
cor.test(oh_CPI$OCProdIdx, oh_CPI$NCCPIx100, method = "spearman") # rank-based (non-parametric)

cor.test(wi_CPI$OCProdIdx, wi_CPI$NCCPIx100, method = "pearson")  # linear correlation
cor.test(wi_CPI$OCProdIdx, wi_CPI$NCCPIx100, method = "spearman") # rank-based (non-parametric)

```

```{r cpi_lm, dependson = "create_cpi", eval = FALSE, echo = FALSE}
lm_ia <- lm(NCCPIx100 ~ OCProdIdx, data = ia_CPI)
summary(lm_ia)

lm_il <- lm(NCCPIx100 ~ OCProdIdx, data = il_CPI)
summary(lm_il)

lm_in <- lm(NCCPIx100 ~ OCProdIdx, data = in_CPI)
summary(lm_in)

lm_mn <- lm(NCCPIx100 ~ OCProdIdx, data = mn_CPI)
summary(lm_mn)

lm_oh <- lm(NCCPIx100 ~ OCProdIdx, data = oh_CPI)
summary(lm_oh)

lm_wi <- lm(NCCPIx100 ~ OCProdIdx, data = wi_CPI)
summary(lm_wi)

```

```{r cpi_lm 2, dependson = "create_cpi", eval = FALSE, echo = FALSE}
ia_CPI$residuals <- residuals(lm_cpi)

outliers <- ia_CPI[abs(ia_CPI$residuals) >2 * sd(ia_CPI$residuals),]

outliers %>%
  group_by(DrainCls) %>%
  summarise(
    mean_CSR2 = mean(OCProdIdx),
    mean_NCCPI = mean(NCCPIx100),
    mean_diff = mean(cpi_diff),
    count = n()
  )

summary(outliers$)
```

```{r cpi_lm, dependson = "create_cpi", eval = FALSE, echo = FALSE}
ggplot(ia_cpi, aes(x = OCProdIdx, y = NCPPIx100)) +
  geom_point(alpha = 0.4) +
  geom_point(data = outliers, color = "red", size = 2) +
  geomabline(slope = 2, intercept = 0, linetype = "dashed") +
  labs(title = CSR2 vs NCCPI: Outliers)

```


```{r low_agree, dependson = "create_cpi", eval = FALSE, echo = FALSE}
threshold <- quantile(ia_CPI$cpi_diff, 0.90)
low_agree <- subset(ia_CPI, cpi_diff >= threshold)

low_agree %>%
  group_by(MUsymbol, DrainCls) %>%
  summarize(mean_CSR2 = mean(OCProdIdx),
            mean_NCCPI = mean(NCCPIx100),
            mean_diff = mean(cpi_diff),
            n=n())

```

```{r explore_cpi, dependson="create_cpi"}

ggplot(ia_CPI, aes(x = OCProdIdx, y = NCCPIx100, color = cpi_diff > 1)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  labs(title = "CSR2 vs NCCPI: Highlighting Low Agreement Points",
       color = "Low Agreement")


g02 <- ggplot(ia_CPI, 
           aes(x = DrainCls, y = cpi_diff, color = cpi_diff > 0.2)) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
g02

g1 <- ggplot(ia_CPI, 
           aes(x = DrainCls, y = cpi_diff, color = cpi_diff > 1)) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
g1

g5 <- ggplot(ia_CPI, 
           aes(x = DrainCls, y = cpi_diff, color = cpi_diff > 5)) + 
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
g5

```

